In [72]:
# Enkf
import numpy as np

In [98]:
N = 10000000
X = np.random.normal(size=[4,N])

In [95]:
d = 3;
Gamma = 5.0

D = np.sqrt(Gamma)*np.random.normal(size=[1,N])+X[0,:]
#The D matrix is h(x, epsilon)


Pt = np.eye(4)


In [96]:
H = np.matrix([1.0,0.0,0.0,0.0])

In [100]:
Xp = X - np.average(X)
Dp = D - np.average(D)
P = 1.0/(N-1.0) * Xp.dot(Xp.T)

print P

K = P*H.T*np.linalg.inv(H*P*H.T + Gamma)
print K

K2 = P*H.T/(H*P*H.T + Gamma)
print K2
print (H*Pt*H.T + Gamma)
K3 = Pt*H.T/(H*Pt*H.T + Gamma)
print K3

Pxd = 1.0/(N-1.0) * Xp.dot(Dp.T)
Pdd = 1.0/(N-1.0) * Dp.dot(Dp.T)

#print Pxd
print Pdd

print Pxd * np.linalg.inv(Pdd)





[[  9.99673492e-01   3.16993777e-04  -2.18692033e-04  -7.45607249e-04]
 [  3.16993777e-04   9.99220992e-01  -4.13368241e-04  -2.09649269e-05]
 [ -2.18692033e-04  -4.13368241e-04   9.99286376e-01   8.93442138e-05]
 [ -7.45607249e-04  -2.09649269e-05   8.93442138e-05   9.99754101e-01]]
[[  1.66621316e-01]
 [  5.28351714e-05]
 [ -3.64506558e-05]
 [ -1.24274638e-04]]
[[  1.66621316e-01]
 [  5.28351714e-05]
 [ -3.64506558e-05]
 [ -1.24274638e-04]]
[[ 6.]]
[[ 0.16666667]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]]
[[ 5.99718977]]
[[  6.81560528e-05]
 [  2.24557384e-04]
 [ -4.50949065e-05]
 [ -8.39622964e-05]]
